# Generated by Django 5.2.3 on 2025-06-11 12:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dob', models.DateField()),
                ('password', models.CharField(max_length=128)),
                ('height', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
    ]
